### ISSUE TITLE
ChangeLog link not working

### ISSUE THREAD

**Issue by honnix** [SWI-Prolog/plweb#11]
ChangeLog link stopped working I think long time ago. What would be the problem? Thanks.

http://www.swi-prolog.org/wiki_edit?location=/download/ChangeLog

**Comment by Anniepoo** [comment]
Is this related to the CDN?

**Comment by JanWielemaker** [comment]
Nope.  It is PlDoc creating the wrong link.

**Comment by JanWielemaker** [comment]
Fixed long ago.  Closing
