### ISSUE TITLE
Title of build issue pages contain html tags

### ISSUE THREAD

**Issue by dram** [SWI-Prolog/plweb#15]
Title of build issue pages contain html tags, e.g. title of this page http://www.swi-prolog.org/build/issues/uuid.html is:

```
Issues with <a class="file" href="/pldoc/doc/swi/library/uuid.pl">library(uuid)</a>
```

**Comment by wouterbeek** [comment]
Issue confirmed.  These issue pages are automatically generated based on Markdown files.  This may therefore be fixed in the Markdown to HTML transformation.

**Comment by JanWielemaker** [comment]
I don't see anything wrong any more.  I recall this was indeed broken.  I recently changed the HTML
and CSS for the title to avoid long titles from obscuring the menu.   Wouldn't really know why that
makes a difference though.

**Comment by wouterbeek** [comment]
@JanWielemaker I can still reproduce this issue (also in incognito tab / with caching of old versions disabled).  Notice the OP is specifically referring to the `<title>` element, so this would not be visible on the page itself (but it is visible in the page's source code):

```html
<title>Issues with <a class="file" href="/pldoc/doc/swi/library/uuid.pl">library(uuid)</a></title>
```

**Comment by JanWielemaker** [comment]
Looked at the title on the page ...  Pushed a fix.  Will be activated with the next release.
