### ISSUE TITLE
Unclear documentation of option value_string_as for json_read_dict/3

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/plweb#22]
Option `value_string_as/1` for `json_read_dict/3` is not well documented.

**Comment by wouterbeek** [comment]
Fixed with e146697ab7aef5a2cd1b49373048c9a49808cfd8.

**Comment by JanWielemaker** [comment]
Seems .tex was not rebuilt.  Fixed the dependencies, so this should be fine with the next release.
