### ISSUE TITLE
Links that previously worked are now broken

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/plweb#24]
For example, to link to `library(http/http_unix_daemon)`, I have for several years used the link:

http://eu.swi-prolog.org/pldoc/doc/swi/library/http/http_unix_daemon.pl

Now, this yields:

<pre>
You don't have permission to access /swi/library/http/http_unix_daemon.pl on this server
</pre>

The only link that now works is:

http://eu.swi-prolog.org/pldoc/doc/_SWI_/library/http/http_unix_daemon.pl

i.e., using `_SWI_` instead of `swi`. However, this cannot be right can it? Please confirm whether this is really the intended new (strange) link. Preferably, I would like to link to a location that remains stable for the foreseeable future. Please note that answers on stackoverflow etc. all rely to some extent on such&nbsp;links.

**Comment by JanWielemaker** [comment]
Yes, it is.  _XYZ_ are symbolic locations that make sure that both backends that use different physical locations can serve the same URIs.   Without, one backend generates links that the other cannot serve and thus you cannot use a CDN.  Before that there was only `/swi/`.  Introducing more of such locations made this too fragile in my opinion.   Sometimes links break ...
