### ISSUE TITLE
Manual page for Prolog Packs is almost empty

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/plweb#25]
The following manual page on Prolog Packs is almost empty: http://www.swi-prolog.org/pldoc/doc_for?object=packages

It is linked to from the "Documentation" menu: `Documentation > Packages`.

It would be better to have a page with more content, explaining what packs are, and links to the list of registered packs.

**Comment by Anniepoo** [comment]
This is not the page for packs.  
This is the old page for 'packages' - things like the http lib that are part of SWI-Prolog.
Having two names so similar is indeed an issue.
Also, when we did the re-org a few old 'user contributed packages' were orphaned. This came up on the mail list a while back. Jan's take, IIRC, was that the old code was not maintained and best deprecated.

**Comment by wouterbeek** [comment]
Oops, that nomenclature fooled me...

Still, there should be some links to packages, a ToC of some kind.

**Comment by JanWielemaker** [comment]
Seems the menu item _DOCUMENTATION/Packages_ is the entry point.   Enhanced description
with 69564d1d320498d331c887ee5b34b3d0790e3492
