### ISSUE TITLE
Empty documentation pages for space package

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/plweb#26]
The predicates from the space packages can still be searched for in the search box at the SWI-Prolog web site, but their documentation pages are empty.  E.g., [this page](http://www.swi-prolog.org/pldoc/doc_for?object=space%3Aspace_assert/2).

**Comment by JanWielemaker** [comment]
They seem no longer searchable.  Closing.  The above link still works, but that is due to packs.  Packs need a different treatment, but that is a different issue.
