### ISSUE TITLE
mangled links in April Fools day page

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/plweb#5]
http://www.swi-prolog.org/AprilFools.html

has a couple links with messed up markdown syntax

SWI-Prolog handles [[Unicode][/pldoc/doc_for?object=section(%27packages/utf8proc.html%27)]] but does not default to EBCDIC

**Comment by JanWielemaker** [comment]
It is a wiki page :) Fixed.

**Comment by Anniepoo** [comment]
Aaargh.... =8cD  Remember the early days of the web, you'd find yourslef doing something
crazy to look up information, then slap your head and think 'I could have used the web!'?

I'm feeling that way now. LOL
